use std::fs;
use std::path::Path;

fn main() {
    let mods_dir = Path::new("mods");
    if !mods_dir.exists() {
        fs::create_dir_all(mods_dir).unwrap();
    }

    let out_dir = std::env::var("OUT_DIR").unwrap();

    let mut modules: Vec<String> = Vec::new();

    for entry in fs::read_dir(mods_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) == Some("rs") {
            if let Some(name) = path.file_stem().and_then(|s| s.to_str()) {
                if !name.starts_with('_') {
                    // Copy .rs into OUT_DIR/ so plain `pub mod` can find it
                    // Module lookup from the generated mods.rs uses OUT_DIR/ as root
                    let dest = Path::new(&out_dir).join(format!("{}.rs", name));
                    fs::copy(&path, &dest).unwrap();
                    modules.push(name.to_string());
                }
            }
        }
    }
    modules.sort();

    let out_path = Path::new(&out_dir).join("mods.rs");
    let mut content = String::from("// Auto-generated by build.rs — do not edit\n\n");
    for m in &modules {
        let src = Path::new(&out_dir)
            .join(format!("{}.rs", m))
            .to_string_lossy()
            .replace('\\', "/");
        content.push_str(&format!(
            "#[path = \"{}\"]\npub mod {};\n",
            src, m
        ));
    }
    content.push('\n');
    content.push_str("pub fn init_all() {\n");
    for m in &modules {
        content.push_str(&format!("    {}::init();\n", m));
    }
    content.push_str("}\n");
    fs::write(out_path, content).unwrap();

    println!("cargo::rerun-if-changed=mods");
    for m in &modules {
        println!(
            "cargo::rerun-if-changed={}",
            Path::new("mods").join(format!("{}.rs", m)).display()
        );
    }
}
